/* タイトル・案内役画像・鑑定リンクはここで変更できます。 */
const SITE_TITLE = '陽月の知って占うタロット豆知識';
const SITE_SUBTITLE = 'クイズで学んで、1枚占いも楽しめる';
const COCONALA_URL = 'https://coconala.com/users/5319059'; // 陽月 Hizukiのプロフィール。
const HIZUKI_IMAGE = 'images/hizuki-sheet.png'; // ご提供のキャラクターシート。CSSで表示範囲を指定します。
const CARD_BACK = 'images/card-back.png';
const GENRES = [{name:'恋愛',note:'あの人との距離、これからのご縁',key:'readingLove'},{name:'仕事',note:'働き方、挑戦、次の一歩',key:'readingWork'},{name:'人間関係',note:'人とのつながり、心地よい距離',key:'readingRelationship'},{name:'今の自分',note:'心の声、今大切にしたいこと',key:'readingSelf'}];
const app = document.getElementById('app');
let genre, chosen, drawn = [], locked = false, choices = [], revealTimer;
// Fisher–Yates: 重複しない抽選にもクイズの選択肢にも使います。
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function guide(text){return `<div class="guide guide-comment fade"><div class="guide-character"><img src="${HIZUKI_IMAGE}" alt="タロットカードを手に微笑む陽月の上半身"></div><div class="guide-bubble"><div class="guide-name">陽月 <span>Hizuki</span></div><p>${text}</p></div></div>`;}
function steps(n){return `<nav class="steps" aria-label="占いの進み具合">${['選ぶ','学ぶ','占う'].map((t,i)=>`<span class="${i===n?'active':''}" ${i===n?'aria-current="step"':''}>${i+1}. ${t}</span>`).join('')}</nav>`;}
function screen(html){app.innerHTML=html;app.classList.remove('fade');void app.offsetWidth;app.classList.add('fade');window.scrollTo({top:0,behavior:'instant'});const h=app.querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
function home(){document.title=SITE_TITLE;screen(`<section class="intro"><div><div class="eyebrow">HIZUKI'S TAROT ROOM</div><h1 class="site-title"><span class="title-owner">陽月の</span><br><span class="title-action">知って占う</span><br><span class="title-main">タロット豆知識</span></h1><p class="site-subtitle">${SITE_SUBTITLE}</p><p>ようこそ、陽月のタロット小部屋へ。<br>今日はあなたに必要なメッセージを、<br>1枚のカードから見てみましょう。</p><button class="primary" id="start">無料で占ってみる</button><div class="small">カードを選んで、学んで、心のヒントを。<br>約3分で楽しめます。</div>${guide('陽月（ひづき）です。<br>タロットが初めての方も、どうぞ気軽に。')}</div><div class="art hizuki-art"><div class="hizuki-portrait"><img src="${HIZUKI_IMAGE}" alt="タロットカードを手に、やさしく微笑む巫女占い師の陽月" fetchpriority="high"><img class="hizuki-blink" src="images/hizuki-blink.png" alt="" aria-hidden="true"></div><div class="art-label">陽月 <span>Hizuki</span></div><p class="hizuki-caption">あなたの想いに、そっと寄り添います。</p></div></section>`);document.getElementById('start').onclick=genreScreen;}
function genreScreen(){clearTimeout(revealTimer);locked=false;screen(`${steps(0)}<section class="panel"><div class="center"><div class="eyebrow">心に浮かぶことを、ひとつ</div><h1>今日は何を占いますか？</h1><p>今、気になっているテーマを選んでください。</p></div><div class="genres">${GENRES.map((g,i)=>`<button class="genre" data-genre="${i}"><strong>${g.name}</strong><span>${g.note}</span></button>`).join('')}</div>${guide('うまく言葉にできなくても大丈夫。<br>いちばん近いテーマを選んでくださいね。')}</section>`);app.querySelectorAll('[data-genre]').forEach(b=>b.onclick=()=>{genre=GENRES[Number(b.dataset.genre)];deckScreen();});}
function deckScreen(){locked=false;drawn=shuffle(CARDS).slice(0,3);screen(`${steps(0)}<section class="panel center"><div class="eyebrow">${genre.name}のタロット</div><h1>直感で、気になる1枚を。</h1><p>ひと呼吸して、カードを選んでください。</p><div class="deck">${drawn.map((c,i)=>`<button class="card-button" data-card="${i}" aria-label="${i+1}枚目のカードを選ぶ"><span class="card-inner"><img class="card-face back" src="${CARD_BACK}" alt="裏向きのタロットカード"><img class="card-face front" src="${c.image}" alt="" aria-hidden="true"></span><span class="card-label">${['左のカード','真ん中のカード','右のカード'][i]}</span></button>`).join('')}</div><p id="deck-status" role="status" class="small">3枚のうち、1枚を選べます。</p><button class="secondary" id="back">テーマを選び直す</button></section>`);app.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>selectCard(Number(b.dataset.card)));document.getElementById('back').onclick=genreScreen;}
function selectCard(index){if(locked)return;locked=true;chosen=drawn[index];app.querySelectorAll('[data-card]').forEach((b,i)=>{b.disabled=true;b.classList.add(i===index?'selected':'unselected');if(i===index){const img=b.querySelector('.front');img.alt=chosen.nameJa;img.removeAttribute('aria-hidden');}});document.getElementById('deck-status').textContent=`あなたのカードは「${chosen.nameJa}」です。`;revealTimer=setTimeout(quizScreen,1100);}
function quizScreen(){choices=shuffle(chosen.quizOptions.map((text,index)=>({text,index})));screen(`${steps(1)}<section class="panel"><div class="card-title"><div class="eyebrow">あなたが選んだカード · ${genre.name}</div><h1>${chosen.roman}　${chosen.nameJa}</h1><div class="en">${chosen.nameEn}</div></div><div class="reveal"><img class="result-card" src="${chosen.image}" alt="${chosen.nameJa}のカード"><div><h2>カードを、少し知る。</h2><p>${chosen.quizQuestion}</p><div class="options">${choices.map((o,i)=>`<button class="option" data-answer="${i}"><b>${'ABC'[i]}</b>${o.text}</button>`).join('')}</div><div id="feedback" aria-live="polite"></div></div></div><div id="reading"></div></section>`);app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)));}
function answer(index){const correct=choices[index].index===chosen.quizAnswer;app.querySelectorAll('[data-answer]').forEach((b,i)=>{b.disabled=true;if(choices[i].index===chosen.quizAnswer)b.classList.add('correct');else if(i===index)b.classList.add('wrong');});document.getElementById('feedback').innerHTML=`<div class="feedback fade"><strong>${correct?'正解です！':'惜しい！正解はこちらです。'}</strong><p class="tags">${chosen.keywords.join(' ／ ')}</p><p>${chosen.explanation}</p><button class="primary" id="show-reading">今の私へのメッセージを見る</button></div>`;document.getElementById('show-reading').onclick=readingScreen;}
function readingScreen(){app.querySelector('.steps').outerHTML=steps(2);document.getElementById('show-reading').disabled=true;document.getElementById('show-reading').textContent='メッセージを表示しました';const reading=document.getElementById('reading');reading.innerHTML=`<section class="reading fade" tabindex="-1"><div class="eyebrow">${genre.name} · 無料ミニ占い</div><h2>今のあなたへのメッセージ</h2><p>それでは、このカードから<br>今のあなたへのメッセージを見てみましょう。</p><p>${chosen[genre.key]}</p><p class="small">この占いはカード1枚による簡易リーディングです。占い結果は未来や他者の気持ちを断定するものではありません。ひとつのヒントとしてお楽しみください。</p></section>${guide('今回の結果は、1枚のカードから読み取った簡易リーディングです。<br><br>同じカードでも、お悩みの内容やお相手との関係、今置かれている状況によって読み方は少しずつ変わります。<br><br>もう少し詳しく知りたい方は、陽月がお話を伺いながら、あなたのお悩みに合わせてゆっくり読み解いていきますね。')}<div class="actions"><a class="primary" href="${COCONALA_URL}" target="_blank" rel="noopener noreferrer">陽月に詳しく占ってもらう</a><div class="small center">ココナラの陽月 Hizuki プロフィールへ（新しいタブで開きます）</div><button class="secondary" id="again">もう一度カードを引く</button></div>`;document.getElementById('again').onclick=genreScreen;reading.querySelector('section').focus({preventScroll:true});reading.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
home();






